### PR TITLE
Implement verification option of random data

### PR DESCRIPTION
**Pull request by dehanj**
Add sub commands;
- generate
- verify

generate sub command has one change. Omitted the the flag `-b` in favor of using bytes as a command, i.e.,
`tkey-random-generator generate 256` to generate 265 bytes of random data.  

The verify sub command takes three input files, and an optional flag if the random data is in binary format (otherwise assumed to be hex representation)

### CODE REVIEW

**Comment by mchack-work** [comment]
Running it two times I get this on the second run:

```
% ./tkey-random-generator generate --port /dev/pts/11 -b 17 -s data
Connecting to device on serial port /dev/pts/11...
Error generating random data: %!w(*fmt.wrapError=&{Could not open /dev/pts/11: Open /dev/pts/11: Serial port busy
 0xc00006a0a0})
```

Perhaps something wasn't closed correctly?

**Comment by mchack-work** [comment]
No problem with unclosed devices anymore.

**Comment by mchack-work** [comment]
See add_verify_mc branch for some suggestions. What do you think?

**Comment by dehanj** [comment]
> See add_verify_mc branch for some suggestions. What do you think?

Looked through your changes in `add_verify_mc`. I think all of them makes sense and looks good. So merge it into this branch and then the PR is good to be merged.

**Review by mchack-work — APPROVED** [review]
Changed:
- Move the CLI command to cmd/tkey-random-generator
- Updated docs
- Move the hash verification before signature verification

Happy with this now.

**Pull request merged**
